library(foreign)
library(ggplot2)
library(lattice)
library(quantreg)
library(lmtest)
library(quantreg)
library(car)
library(bstats)
library(texreg)
library(rms)
library(erer)
library(mlogit)
library(MASS)
library("sampleSelection")

setwd ("C:/Econometrics Applications")

crime <- read.dta ("crime12.dta")
summary(crime)

ols.lcrmrte <- lm(formula= lcrmrte ~ lprbarr + lprbconv +lprbpris + lavgsen + lpolpc +d83 + d84 + d85 + d86 + d87  , data=crime)
summary(ols.lcrmrte)
